/**
 * Do not edit directly, this file was auto-generated.
 */

export const BackgroundPrimary = "#f6f6f6"; // Background/primary — page surface
export const BackgroundSecondary = "#dfe3e4"; // Background/secondary
export const BackgroundTertiary = "#c1c8cc"; // Background/tertiary
export const BackgroundDisabled = "#dfe3e4"; // Background/disabled
export const BackgroundInverse = "#181b1d"; // Background/inverse
export const BackgroundInverseHover = "#161515"; // Background/inverse-hover
export const BackgroundSolid = "#ffffff"; // Background/solid — always pure white/black
export const BackgroundBrand = "#dfa7ab"; // Background/brand — primary button
export const BackgroundBrandHover = "#dd9299"; // Background/brand-hover
export const BackgroundBrandSubtle = "#e5bbbe"; // Background/brand-subtle
export const BackgroundSuccess = "#26637f"; // Background/success
export const BackgroundSuccessSubtle = "#ebeef0"; // Background/success-subtle
export const BackgroundWarning = "#bb031e"; // Background/warning
export const BackgroundWarningSubtle = "#efe5e4"; // Background/warning-subtle
export const BackgroundError = "#b32228"; // Background/error
export const BackgroundErrorSubtle = "#eee5e4"; // Background/error-subtle
export const BackgroundSelection = "#efe3e4"; // Background/selection
export const TextPrimary = "#181b1d"; // Text/primary
export const TextSecondary = "#3e4951"; // Text/secondary
export const TextTertiary = "#5e7582"; // Text/tertiary
export const TextDisabled = "#a9b5bb"; // Text/disabled
export const TextPlaceholder = "#5e7582"; // Text/placeholder
export const TextOnInverse = "#f6f6f6"; // Text/on-inverse — text on dark surface
export const TextOnBrand = "#181b1d"; // Text/on-brand — text on brand surface
export const TextInverse = "#161515"; // Text/inverse
export const TextBrand = "#8c545a"; // Text/brand
export const TextLink = "#8c545a"; // Text/link
export const TextLinkHover = "#513235"; // Text/link hover
export const TextSuccess = "#26637f"; // Text/success
export const TextWarning = "#860006"; // Text/warning
export const TextError = "#800211"; // Text/error
export const TextButtonLarge = "16px"; // text/button/large
export const TextButtonMedium = "14px"; // text/button/medium
export const TextButtonSmall = "12px"; // text/button/small
export const ForegroundPrimary = "#181b1d"; // Foreground/primary — icons on surface
export const ForegroundSecondary = "#2b3239"; // Foreground/secondary
export const ForegroundTertiary = "#3e4951"; // Foreground/tertiary
export const ForegroundQuaternary = "#5e7582"; // Foreground/quaternary
export const ForegroundDisabled = "#a9b5bb"; // Foreground/disabled
export const ForegroundOnInverse = "#f6f3f3"; // Foreground/on-inverse — icons on dark surface
export const ForegroundOnBrand = "#181b1d"; // Foreground/on-brand — icons on brand surface
export const ForegroundBrand = "#dfa7ab"; // Foreground/brand
export const ForegroundBrandSubtle = "#e5bbbe"; // Foreground/brand-subtle
export const ForegroundSuccess = "#26637f"; // Foreground/success
export const ForegroundWarning = "#bb031e"; // Foreground/warning
export const ForegroundError = "#b32228"; // Foreground/error
export const BorderPrimary = "#5e7582"; // Border/primary
export const BorderSecondary = "#a9b5bb"; // Border/secondary
export const BorderSubtle = "#dfe3e4"; // Border/subtle
export const BorderDisabled = "#a9b5bb"; // Border/disabled
export const BorderHard = "#181b1d"; // Border/hard
export const BorderInteractive = "#2b3239"; // Border/interactive
export const BorderBrand = "#8c545a"; // Border/brand
export const BorderBrandSubtle = "#e5bbbe"; // Border/brand-subtle
export const BorderSuccess = "#4694b8"; // Border/success
export const BorderWarning = "#bb031e"; // Border/warning
export const BorderError = "#b32228"; // Border/error
export const SpecializedViz1 = "#dfa7ab"; // Specialized/viz-1
export const SpecializedViz2 = "#80919c"; // Specialized/viz-2
export const SpecializedViz3 = "#26637f"; // Specialized/viz-3
export const SpecializedVizGrid = "#dfe3e4"; // Specialized/viz-grid
export const SpecializedSkeletonBase = "#dfe3e4"; // Specialized/skeleton-base
export const SpecializedSkeletonShimmer = "#f6f6f6"; // Specialized/skeleton-shimmer
export const SpecializedFocusRing = "#dfa7ab"; // Specialized/focus-ring
export const SpecializedShadowColor = "#80919c"; // Specialized/shadow-color
export const SpecializedBgOverlay = "#80919c"; // Specialized/bg-overlay
export const FontFamilyDisplay =
  '"neue-haas-grotesk-display", system-ui, sans-serif'; // Font/family/display
export const FontFamilyText = '"neue-haas-grotesk-text", system-ui, sans-serif'; // Font/family/text — body copy
export const FontWeightMedium = "500"; // Font/weight/medium
export const RadiusMd = "4px"; // radius/md
export const RadiusSm = "2px"; // radius/sm
export const RadiusLg = "8px"; // radius/lg
export const ButtonGapLg = "10px"; // button/gap/lg
export const ButtonGapMd = "8px"; // button/gap/md
export const ButtonGapSm = "6px"; // button/gap/sm
export const ButtonPaddingHorizontalLg = "24px"; // button/padding/horizontal/lg
export const ButtonPaddingHorizontalMd = "20px"; // button/padding/horizontal/md
export const ButtonPaddingHorizontalSm = "12px"; // button/padding/horizontal/sm
export const ButtonPaddingVerticalLg = "16px"; // button/padding/vertical/lg
export const ButtonPaddingVerticalMd = "14px"; // button/padding/vertical/md
export const ButtonPaddingVerticalSm = "8px"; // button/padding/vertical/sm
export const ButtonBorderWeight = "1px"; // button/border-weight
export const InputPaddingVerticalSm = "7px"; // input/padding/vertical/sm
export const InputPaddingVerticalMd = "14px"; // input/padding/vertical/md
export const InputPaddingHorizontalSm = "10px"; // input/padding/horizontal/sm
export const InputPaddingHorizontalMd = "16px"; // input/padding/horizontal/md
export const InputGapSm = "6px"; // input/gap/sm
export const InputGapMd = "10px"; // input/gap/md
export const InputBorderWeight = "1px"; // input/border-weight
export const InputFocusSpread = "3px"; // input/focus spread
export const AlertGap = "16px"; // alert/gap
export const AlertPaddingHorizontal = "16px"; // alert/padding/horizontal
export const AlertPaddingVertical = "16px"; // alert/padding/vertical
export const BadgeGap = "8px"; // badge/gap
export const BadgePaddingHorizontal = "12px"; // badge/padding/horizontal
export const BadgePaddingVertical = "6px"; // badge/padding/vertical
export const BorderWeight = "1px"; // global border weight
export const ContainerWidthXs = "420px"; // container-width/xs
export const ContainerWidthSm = "720px"; // container-width/sm
export const ContainerWidthMd = "1280px"; // container-width/md
export const ContainerWidthLg = "1440px"; // container-width/lg
export const ContainerWidthXl = "1680px"; // container-width/xl
export const TooltipPaddingVertical = "6px"; // tooltip/padding/vertical
export const TooltipPaddingHorizontal = "8px"; // tooltip/padding/horizontal
